name: Build Artifacts
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Base64
        run: sudo apt-get install -y coreutils
      - name: Build Artifacts
        run: ./build.sh runtime-compile.rb
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: run.sh